

















local function Overlay(dst, src)
    for k, v in pairs(src) do
        if type(v) == "table" and type(dst[k]) == "table" then
            Overlay(dst[k], v)
        else
            dst[k] = v
        end
    end
end

local TUNED = {
    Camera = {
        dynamicPitch = false,
        enabled = true,
        focusEnemy = false,
        focusInteract = true,
        headMovement = false,
        maxZoomFactor = 2.6,
        rotateResumeDelay = 4,
        shoulderOffset = 0,
        situations = {
            afk = {
                enabled = true,
                fadeUI = true,
                overrideShoulder = false,
                restoreZoom = true,
                rotate = true,
                rotateSpeed = 5,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 10,
            },
            city = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = true,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 1,
                swing = 0,
                swingBack = true,
                zoom = 3,
            },
            combat = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 10,
            },
            dialogue = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = true,
                restoreZoom = true,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 1.5,
                swing = 80,
                swingBack = true,
                zoom = 2,
            },
            fishing = {
                enabled = false,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = true,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 8,
            },
            indoors = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = true,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 2,
                swing = 0,
                swingBack = true,
                zoom = 3,
            },
            instance = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 7,
            },
            mounted = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 15,
            },
            pvp = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 14,
            },
            swimming = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = true,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 14,
            },
            taxi = {
                enabled = true,
                fadeUI = true,
                overrideShoulder = false,
                restoreZoom = true,
                rotate = true,
                rotateSpeed = 4,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 20,
            },
            world = {
                enabled = true,
                fadeUI = false,
                overrideShoulder = false,
                restoreZoom = false,
                rotate = false,
                rotateSpeed = 6,
                shoulder = 0,
                swing = 0,
                swingBack = true,
                zoom = 5,
            },
        },
        transitionTime = 0.8,
        zoomSpeed = 20,
    },
    ControllerTarget = {
        target = {
            auraMax = 16,
            auraPerRow = 8,
            auraSize = 12,
            auraTextScale = 0.3,
            auraTimers = false,
            auras = "below",
            enabled = true,
            healthHeight = 9,
            healthText = "number",
            iconScale = 1.05,
            point = {
                x = 1063.888549804688,
                y = 1184,
            },
            powerHeight = 5,
            scale = 2.05,
            showBuffs = true,
            showDebuffs = true,
            showFaction = true,
            showLevel = true,
            showName = true,
            showPower = true,
            showRole = true,
            textScale = 0.8,
            width = 589,
        },
        tot = {
            auraMax = 6,
            auraPerRow = 6,
            auraSize = 16,
            auraTextScale = 1,
            auraTimers = false,
            auras = "none",
            enabled = true,
            healthHeight = 6,
            healthText = "none",
            iconScale = 0.9500000000000001,
            point = {
                x = 1066.112060546875,
                y = 1146.66650390625,
            },
            powerHeight = 2,
            scale = 2.05,
            showBuffs = true,
            showDebuffs = false,
            showFaction = false,
            showLevel = false,
            showName = true,
            showPower = true,
            showRole = true,
            textScale = 0.75,
            width = 152,
        },
    },
    Dialogue = {
        enabled = true,
        fontSize = 24,
        holdTime = 6,
        locked = true,
        opacity = 1,
        point = "BOTTOM",
        revealInstant = false,
        revealSpeed = 50,
        width = 700,
        x = -4.999672889709473,
        y = 32.88916015625,
    },
    Orbs = {
        health = {
            artPath = "",
            artSize = 160,
            artX = 0,
            artY = 0,
            bgAlpha = 0.6,
            colorMode = "green",
            customColor = { 1, 1, 1 },
            decor = "faction",
            decorColor = { 1, 1, 1 },
            decorFront = false,
            decorScale = 2.1,
            decorX = -62,
            decorY = 31,
            direction = "up",
            enabled = true,
            glass = true,
            hideWhenFull = true,
            locked = true,
            oocAlpha = 1,
            plate = true,
            plateColor = { 1, 1, 1 },
            ring = true,
            ringAlpha = 1,
            ringArt = "orb",
            ringBlend = "auto",
            ringColor = { 1, 1, 1 },
            ringDesat = false,
            ringScale = 1,
            ringSeeded = true,
            ringSpin = 0,
            ringX = 0,
            ringY = 0,
            scale = 1.15,
            showInCombat = true,
            size = 110,
            unitPoint = {
                x = 82.7777830128507,
                y = 0,
            },
        },
        linkFull = false,
        resource = {
            artPath = "",
            artSize = 160,
            artX = -1,
            artY = 0,
            bgAlpha = 0.6,
            colorMode = "power",
            customColor = { 1, 1, 1 },
            decor = "faction",
            decorColor = { 1, 1, 1 },
            decorFront = false,
            decorScale = 2.1,
            decorX = 63,
            decorY = 31,
            direction = "up",
            enabled = true,
            glass = true,
            hideWhenFull = false,
            locked = true,
            oocAlpha = 1,
            plate = true,
            plateColor = { 1, 1, 1 },
            ring = true,
            ringAlpha = 1,
            ringArt = "orb",
            ringBlend = "auto",
            ringColor = { 1, 1, 1 },
            ringDesat = false,
            ringScale = 1,
            ringSeeded = true,
            ringSpin = 0,
            ringX = 0,
            ringY = 0,
            scale = 1.15,
            showInCombat = true,
            size = 110,
            unitPoint = {
                x = 83.3324765827565,
                y = 0,
            },
        },
    },
    ResourcePips = {
        colorMode = "power",
        customColor = { 1, 0.85, 0.3 },
        dimAlpha = 0,
        enabled = true,
        gap = 4,
        layout = "ring",
        orientation = "horizontal",
        point = {
            x = 1921.665893554688,
            y = 126.0000076293945,
        },
        radius = 41,
        ring = true,
        ringAdd = false,
        ringAlpha = 1,
        ringArt = "rune",
        ringBlend = "auto",
        ringColor = { 1, 0.5, 0 },
        ringDesat = false,
        ringScale = 0.9,
        ringSize = 0,
        ringSpin = 4,
        ringUnlitAlpha = 0,
        ringX = 0,
        ringY = 0,
        scale = 3,
        show = "controller",
        size = 15,
        spread = 0.6000000000000001,
        start = 12,
    },
    Visibility = {
        bagBar = {
            hideResting = false,
            mode = "nocombat",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        blizzXP = {
            hideResting = true,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            softAlpha = 0.5,
        },
        buffs = {
            hideResting = true,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        castBar = {
            hideResting = false,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        controllerButtons = {
            hideResting = false,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        debuffs = {
            hideResting = true,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        microMenu = {
            hideResting = false,
            mode = "nocombat",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        minimap = {
            hideResting = false,
            mode = "nocombat",
            oocAlpha = 1,
            showSoft = false,
            softAlpha = 0.5,
        },
        orbHealth = {
            hideResting = true,
            mode = "always",
            oocAlpha = 0,
            showSoft = true,
            showTarget = true,
            softAlpha = 0.05,
            targetAlpha = 0.8500000000000001,
        },
        orbResource = {
            hideResting = true,
            mode = "always",
            oocAlpha = 0,
            showSoft = true,
            showTarget = true,
            softAlpha = 0.05,
            targetAlpha = 0.8500000000000001,
        },
        resourcePips = {
            hideResting = true,
            mode = "always",
            oocAlpha = 0,
            showSoft = false,
            showTarget = true,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        resourcePipsRing = {
            hideResting = false,
            mode = "always",
            oocAlpha = 0,
            showSoft = false,
            showTarget = true,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        statusBar = {
            hideResting = false,
            mode = "nocombat",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
        tot = {
            hideResting = false,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            softAlpha = 0.5,
        },
        xpBar = {
            hideResting = true,
            mode = "always",
            oocAlpha = 1,
            showSoft = false,
            showTarget = false,
            softAlpha = 0.5,
            targetAlpha = 1,
        },
    },
}

for name, values in pairs(TUNED) do
    ThugUI.defaults[name] = ThugUI.defaults[name] or {}
    Overlay(ThugUI.defaults[name], values)
end
